In [ ]:
1)	Define the following metrics and perform the following operations
i)	Write a Python program using Python Lists
ii)	Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].


In [1]:
# Define matrices A, B, C using Python lists
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Function to add two matrices
def add_matrices(matrix1, matrix2):
    result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    return result

# Add matrices A and B
result_add_AB = add_matrices(A, B)

# Print the result of addition
print("Matrix A + Matrix B:")
for row in result_add_AB:
    print(row)

# Example: Add matrices A, B, and C
result_add_ABC = add_matrices(result_add_AB, C)
print("\nMatrix A + Matrix B + Matrix C:")
for row in result_add_ABC:
    print(row)


Matrix A + Matrix B:
[6.9061, 6.444100000000001, 6.3575]
[4.3233, 6.79, 7.242]
[2.2221, 4.239, 11.0321]

Matrix A + Matrix B + Matrix C:
[10.0304, 9.543000000000001, 9.4831]
[6.9954, 10.4685, 11.143699999999999]
[3.3475, 7.1346, 16.9508]


In [ ]:
#ii)	Write a Python program and NumPy

In [3]:
import numpy as np

# Define matrices A, B, and C using NumPy arrays
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Add matrices A and B
result_add_AB = A + B

# Print the result of addition
print("Matrix A + Matrix B (NumPy):")
print(result_add_AB)

# Add matrices A, B, and C
result_add_ABC = A + B + C

# Print the result of addition
print("\nMatrix A + Matrix B + Matrix C (NumPy):")
print(result_add_ABC)


Matrix A + Matrix B (NumPy):
[[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

Matrix A + Matrix B + Matrix C (NumPy):
[[10.0304  9.543   9.4831]
 [ 6.9954 10.4685 11.1437]
 [ 3.3475  7.1346 16.9508]]


In [ ]:
2)	Write a Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}
II.	Iterate using a for loop
III.	Iterate using for loop and range
IV.	List Comprehension
V.	Enumerate
VI.	Iter function and next function
VII.	Map function
VIII.	Using zip
IX.	Using NumPy Module


In [5]:
# Create the list
numbers = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


In [7]:
# Iterate through the list using a simple for loop
print("Iteration using for loop:")
for num in numbers:
    print(num)


Iteration using for loop:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


In [9]:
# Iterate through the list using a for loop and range
print("\nIteration using for loop and range:")
for i in range(len(numbers)):
    print(numbers[i])



Iteration using for loop and range:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


In [11]:
# Using list comprehension to create a new list of squared numbers
squared_numbers = [num ** 2 for num in numbers]
print("\nList comprehension (squared numbers):")
print(squared_numbers)



List comprehension (squared numbers):
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


In [13]:
# Using enumerate to iterate through the list with an index
print("\nUsing enumerate:")
for index, num in enumerate(numbers):
    print(f"Index {index}: {num}")



Using enumerate:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456


In [15]:
# Using iter() and next() to manually iterate through the list
print("\nUsing iter() and next():")
numbers_iter = iter(numbers)
try:
    while True:
        print(next(numbers_iter))
except StopIteration:
    pass  # When iteration finishes



Using iter() and next():
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


In [17]:
# Using map() to create a new list of numbers multiplied by 2
multiplied_numbers = list(map(lambda x: x * 2, numbers))
print("\nUsing map function (numbers * 2):")
print(multiplied_numbers)



Using map function (numbers * 2):
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]


In [19]:
# Using zip to combine two lists element-wise
numbers2 = [i for i in range(10, 20)]  # Another list to zip with
print("\nUsing zip (numbers with another list):")
for num1, num2 in zip(numbers, numbers2):
    print(f"Original: {num1}, Zipped: {num2}")



Using zip (numbers with another list):
Original: 1225, Zipped: 10
Original: 4986, Zipped: 11
Original: 6789, Zipped: 12
Original: 7890, Zipped: 13
Original: 2345, Zipped: 14
Original: 6783, Zipped: 15
Original: 987, Zipped: 16
Original: 1234, Zipped: 17
Original: 8765, Zipped: 18
Original: 3456, Zipped: 19


In [21]:
import numpy as np

# Convert the list to a NumPy array and perform operations
numbers_np = np.array(numbers)

# Example operation: add 100 to each element
numbers_np_plus_100 = numbers_np + 100
print("\nUsing NumPy (numbers + 100):")
print(numbers_np_plus_100)



Using NumPy (numbers + 100):
[1325 5086 6889 7990 2445 6883 1087 1334 8865 3556]


In [ ]:
3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [23]:
import itertools

# Define the lists A, B, C, D, E
A = ['a1', 'a2', 'a3']
B = ['b1', 'b2', 'b3']
C = ['c1', 'c2', 'c3']
D = ['d1', 'd2', 'd3']
E = ['e1', 'e2', 'e3']

# Combine all lists into one 
combined_list = A + B + C + D + E

# 1. Compute all combinations of 3 elements from the combined list
combinations = list(itertools.combinations(combined_list, 3))
print("All combinations of 3 elements:")
for comb in combinations:
    print(comb)

# 2. Compute all permutations of 3 elements from the combined list
permutations = list(itertools.permutations(combined_list, 3))
print("\nAll permutations of 3 elements:")
for perm in permutations:
    print(perm)




All combinations of 3 elements:
('a1', 'a2', 'a3')
('a1', 'a2', 'b1')
('a1', 'a2', 'b2')
('a1', 'a2', 'b3')
('a1', 'a2', 'c1')
('a1', 'a2', 'c2')
('a1', 'a2', 'c3')
('a1', 'a2', 'd1')
('a1', 'a2', 'd2')
('a1', 'a2', 'd3')
('a1', 'a2', 'e1')
('a1', 'a2', 'e2')
('a1', 'a2', 'e3')
('a1', 'a3', 'b1')
('a1', 'a3', 'b2')
('a1', 'a3', 'b3')
('a1', 'a3', 'c1')
('a1', 'a3', 'c2')
('a1', 'a3', 'c3')
('a1', 'a3', 'd1')
('a1', 'a3', 'd2')
('a1', 'a3', 'd3')
('a1', 'a3', 'e1')
('a1', 'a3', 'e2')
('a1', 'a3', 'e3')
('a1', 'b1', 'b2')
('a1', 'b1', 'b3')
('a1', 'b1', 'c1')
('a1', 'b1', 'c2')
('a1', 'b1', 'c3')
('a1', 'b1', 'd1')
('a1', 'b1', 'd2')
('a1', 'b1', 'd3')
('a1', 'b1', 'e1')
('a1', 'b1', 'e2')
('a1', 'b1', 'e3')
('a1', 'b2', 'b3')
('a1', 'b2', 'c1')
('a1', 'b2', 'c2')
('a1', 'b2', 'c3')
('a1', 'b2', 'd1')
('a1', 'b2', 'd2')
('a1', 'b2', 'd3')
('a1', 'b2', 'e1')
('a1', 'b2', 'e2')
('a1', 'b2', 'e3')
('a1', 'b3', 'c1')
('a1', 'b3', 'c2')
('a1', 'b3', 'c3')
('a1', 'b3', 'd1')
('a1', 'b3', 'd2')

In [ ]:
4)	Using the same list use itertools compute permutations and combinations 

In [25]:
import itertools

# Define the lists A, B, C, D, E
A = ['a1', 'a2', 'a3']
B = ['b1', 'b2', 'b3']
C = ['c1', 'c2', 'c3']
D = ['d1', 'd2', 'd3']
E = ['e1', 'e2', 'e3']

# Combine all lists into one
combined_list = A + B + C + D + E

# 1. Compute all combinations of 3 elements from the combined list
combinations = list(itertools.combinations(combined_list, 3))
print("All combinations of 3 elements:")
for comb in combinations:
    print(comb)

# 2. Compute all permutations of 3 elements from the combined list
permutations = list(itertools.permutations(combined_list, 3))
print("\nAll permutations of 3 elements:")
for perm in permutations:
    print(perm)


All combinations of 3 elements:
('a1', 'a2', 'a3')
('a1', 'a2', 'b1')
('a1', 'a2', 'b2')
('a1', 'a2', 'b3')
('a1', 'a2', 'c1')
('a1', 'a2', 'c2')
('a1', 'a2', 'c3')
('a1', 'a2', 'd1')
('a1', 'a2', 'd2')
('a1', 'a2', 'd3')
('a1', 'a2', 'e1')
('a1', 'a2', 'e2')
('a1', 'a2', 'e3')
('a1', 'a3', 'b1')
('a1', 'a3', 'b2')
('a1', 'a3', 'b3')
('a1', 'a3', 'c1')
('a1', 'a3', 'c2')
('a1', 'a3', 'c3')
('a1', 'a3', 'd1')
('a1', 'a3', 'd2')
('a1', 'a3', 'd3')
('a1', 'a3', 'e1')
('a1', 'a3', 'e2')
('a1', 'a3', 'e3')
('a1', 'b1', 'b2')
('a1', 'b1', 'b3')
('a1', 'b1', 'c1')
('a1', 'b1', 'c2')
('a1', 'b1', 'c3')
('a1', 'b1', 'd1')
('a1', 'b1', 'd2')
('a1', 'b1', 'd3')
('a1', 'b1', 'e1')
('a1', 'b1', 'e2')
('a1', 'b1', 'e3')
('a1', 'b2', 'b3')
('a1', 'b2', 'c1')
('a1', 'b2', 'c2')
('a1', 'b2', 'c3')
('a1', 'b2', 'd1')
('a1', 'b2', 'd2')
('a1', 'b2', 'd3')
('a1', 'b2', 'e1')
('a1', 'b2', 'e2')
('a1', 'b2', 'e3')
('a1', 'b3', 'c1')
('a1', 'b3', 'c2')
('a1', 'b3', 'c3')
('a1', 'b3', 'd1')
('a1', 'b3', 'd2')